version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "flask db upgrade &&
             flask run --host=0.0.0.0"
    user: root
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db/email_scheduler
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 30s
      retries: 3

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: email_scheduler
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A app.tasks.email_tasks.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db/email_scheduler
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    env_file:
      - .env


